/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/data-enricher/wrangler.jsonc --include-runtime=false workers/data-enricher/worker-configuration.d.ts` (hash: 22b1fdbd136d7e63c3810756e662a8d2)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	MCP_SERVERS: "";
	OWNER_EMAIL: "allisteraall@gmail.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MCP_SERVERS" | "OWNER_EMAIL">> {}
}
