/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/data-enricher/wrangler.jsonc --include-runtime=false workers/data-enricher/worker-configuration.d.ts` (hash: 9fcfc4de2678d064437c2477e1fc8453)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	TODOIST_MCP_URL: "https://ai.todoist.net/mcp";
	AI_MODEL: "gpt-5.6-luna";
	OWNER_EMAIL: "allisteraall@gmail.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TODOIST_MCP_URL" | "AI_MODEL" | "OWNER_EMAIL">> {}
}
