/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/data-enricher/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/data-enricher/worker-configuration.d.ts` (hash: dc369070554c7512513d5e714da21ee1)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	AI_MODEL: "gpt-5.6-luna";
	OWNER_EMAIL: "allisteraall@gmail.com";
	SENTRY_ENVIRONMENT: "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_MODEL" | "OWNER_EMAIL" | "SENTRY_ENVIRONMENT">> {}
}
