/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cookie-web-search/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/cookie-web-search/worker-configuration.d.ts` (hash: 32c4cb7d287e93da1d507b98ce1f1a24)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	AUTH0_DOMAIN: "dev-ixcl1rgxrlgeqrvs.us.auth0.com";
	AUTH0_AUDIENCE: "https://cookie-web/api";
	ALLOWED_ORIGIN: "https://mail.infinitywave.online";
	SENTRY_ENVIRONMENT: "production";
	MEILISEARCH_URL: "";
	MEILISEARCH_INDEX: "messages";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH0_DOMAIN" | "AUTH0_AUDIENCE" | "ALLOWED_ORIGIN" | "SENTRY_ENVIRONMENT" | "MEILISEARCH_URL" | "MEILISEARCH_INDEX">> {}
}
