/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b910dec827cd035ed4c22a1a39557414)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	FORWARD_TO: "allisteraall@gmail.com";
	OWNER_EMAIL: "allisteraall@gmail.com";
	SENTRY_ENVIRONMENT: "production";
	DATABASE_URL: string;
	OPENAI_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FORWARD_TO" | "OWNER_EMAIL" | "SENTRY_ENVIRONMENT" | "DATABASE_URL" | "OPENAI_API_KEY">> {}
}
