/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cookie-web-tasks/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/cookie-web-tasks/worker-configuration.d.ts` (hash: fa3dd4f95507ee3900a86a152ef7b40e)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	AUTH0_DOMAIN: "dev-ixcl1rgxrlgeqrvs.us.auth0.com";
	AUTH0_AUDIENCE: "https://cookie-web/api";
	ALLOWED_ORIGIN: "https://mail.infinitywave.online";
	SENTRY_ENVIRONMENT: "production";
	OWNER_EMAIL: "allisteraall@gmail.com";
	ENRICHER: Fetcher /* data-enricher */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH0_DOMAIN" | "AUTH0_AUDIENCE" | "ALLOWED_ORIGIN" | "SENTRY_ENVIRONMENT" | "OWNER_EMAIL">> {}
}
