/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cookie-web-tasks/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/cookie-web-tasks/worker-configuration.d.ts` (hash: 328aa98e5e591939becffd47671b62df)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	AUTH0_DOMAIN: "dev-ixcl1rgxrlgeqrvs.us.auth0.com";
	AUTH0_AUDIENCE: "https://cookie-web/api";
	ALLOWED_ORIGIN: "https://mail.infinitywave.online";
	SENTRY_ENVIRONMENT: "production";
	ENRICHER_RUN_URL: "https://data-enricher.cloudflare-581.workers.dev/run";
	OWNER_EMAIL: "allisteraall@gmail.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH0_DOMAIN" | "AUTH0_AUDIENCE" | "ALLOWED_ORIGIN" | "SENTRY_ENVIRONMENT" | "ENRICHER_RUN_URL" | "OWNER_EMAIL">> {}
}
