/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/mail-app-ingest/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/mail-app-ingest/worker-configuration.d.ts` (hash: e22724733a3139a8b40c7203984981a0)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	FORWARD_TO: "allisteraall@gmail.com";
	OWNER_EMAIL: "allisteraall@gmail.com";
	AI_MODEL: "gpt-5.6-luna";
	SENTRY_ENVIRONMENT: "production";
	CLOUDFLARE_ACCOUNT_ID: "b581e48529728e578cea1d0b0a2ecab3";
	AI_GATEWAY_ID: "cookie";
	MEILISEARCH_URL: "https://ms-52028f71df74-53700.lon.meilisearch.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FORWARD_TO" | "OWNER_EMAIL" | "AI_MODEL" | "SENTRY_ENVIRONMENT" | "CLOUDFLARE_ACCOUNT_ID" | "AI_GATEWAY_ID" | "MEILISEARCH_URL">> {}
}
