/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/mail-app-ingest/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/mail-app-ingest/worker-configuration.d.ts` (hash: 376f9926b4f716039c5c197923cc9916)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	FORWARD_TO: "allisteraall@gmail.com";
	OWNER_EMAIL: "allisteraall@gmail.com";
	AI_MODEL: "gpt-5.6-luna";
	SENTRY_ENVIRONMENT: "production";
	MEILISEARCH_URL: "";
	MEILISEARCH_INDEX: "messages";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FORWARD_TO" | "OWNER_EMAIL" | "AI_MODEL" | "SENTRY_ENVIRONMENT" | "MEILISEARCH_URL" | "MEILISEARCH_INDEX">> {}
}
