/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cookie-web-notifications/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/cookie-web-notifications/worker-configuration.d.ts` (hash: 5e046aaa281f526bf55a557ae89603bd)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	AUTH0_DOMAIN: "auth.infinitywave.online,dev-ixcl1rgxrlgeqrvs.us.auth0.com";
	AUTH0_AUDIENCE: "https://cookie-web/api";
	ALLOWED_ORIGIN: "https://mail.infinitywave.online";
	SENTRY_ENVIRONMENT: "production";
	NTFY_BASE_URL: "https://ntfy.allisterantosik.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH0_DOMAIN" | "AUTH0_AUDIENCE" | "ALLOWED_ORIGIN" | "SENTRY_ENVIRONMENT" | "NTFY_BASE_URL">> {}
}
