/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/scheduled-send-flusher/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/scheduled-send-flusher/worker-configuration.d.ts` (hash: 605ac111f937bf473307d12ae1918f65)
interface __BaseEnv_Env {
	COOKIE_WEB_FLUSH_URL: "https://mail.infinitywave.online/api/send?resource=flush";
	SENTRY_ENVIRONMENT: "production";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COOKIE_WEB_FLUSH_URL" | "SENTRY_ENVIRONMENT">> {}
}
