/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/scheduled-send-flusher/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/scheduled-send-flusher/worker-configuration.d.ts` (hash: 4d352f5e0b73ec9e4fe025f8888754a2)
interface __BaseEnv_Env {
	SENTRY_ENVIRONMENT: "production";
	SEND: Fetcher /* cookie-web-send */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SENTRY_ENVIRONMENT">> {}
}
