/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cookie-web-ai/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/cookie-web-ai/worker-configuration.d.ts` (hash: 7c0cfdf54fd5729550e17cee1188ae13)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	AUTH0_DOMAIN: "auth.infinitywave.online,dev-ixcl1rgxrlgeqrvs.us.auth0.com";
	AUTH0_AUDIENCE: "https://cookie-web/api";
	ALLOWED_ORIGIN: "https://mail.infinitywave.online";
	SENTRY_ENVIRONMENT: "production";
	CLOUDFLARE_ACCOUNT_ID: "b581e48529728e578cea1d0b0a2ecab3";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH0_DOMAIN" | "AUTH0_AUDIENCE" | "ALLOWED_ORIGIN" | "SENTRY_ENVIRONMENT" | "CLOUDFLARE_ACCOUNT_ID">> {}
}
