/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cookie-mcp/wrangler.jsonc --env-file=.wrangler-types.env --include-runtime=false workers/cookie-mcp/worker-configuration.d.ts` (hash: e054b5707a7aefe7fc583f74c79ad0fa)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	AUTH0_DOMAIN: "auth.infinitywave.online";
	AUTH0_AUDIENCE: "https://mcp.infinitywave.online/mcp";
	MCP_RESOURCE: "https://mcp.infinitywave.online/mcp";
	SENTRY_ENVIRONMENT: "production";
	EMAILS: Service /* entrypoint Internal from cookie-web-emails */;
	MESSAGES: Service /* entrypoint Internal from cookie-web-messages */;
	LABELS: Service /* entrypoint Internal from cookie-web-labels */;
	SEARCH: Service /* entrypoint Internal from cookie-web-search */;
	DRAFTS: Service /* entrypoint Internal from cookie-web-drafts */;
	SEND: Service /* entrypoint Internal from cookie-web-send */;
	CALENDAR: Service /* entrypoint Internal from cookie-web-calendar */;
	TASKS: Service /* entrypoint Internal from cookie-web-tasks */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH0_DOMAIN" | "AUTH0_AUDIENCE" | "MCP_RESOURCE" | "SENTRY_ENVIRONMENT">> {}
}
